### PR TITLE
Makes run_list configureable

### PR DESCRIPTION
**Pull request by jonsmorrow**

### CODE REVIEW

**Comment by tylercloke** [comment]
So this is so you can run additional things on the builders in addition to the default run list delivery needs its builders to run in order for delivery to function properly? If so, is there a way to enforce that delivery_build is included so we don't accidentally override that needed run list?

**Comment by jonsmorrow** [comment]
Not easily unfortunately. terraform has pretty limited variable typings.

**Comment by afiune** [comment]
I agree with @tylercloke comment. We have to be prescriptive with the run-list but flexible at the same time. If they want to add things we just have that variable available, something like `recipes` that will add specific recipes to the run_list plus `delivery_build` that should always be there.

**Comment by tylercloke** [comment]
If it is not possible to do the above, we definitely need to document this very visibly.

**Comment by afiune** [comment]
It is possible and @jonsmorrow has some code to add things at the beginning of the run_list..

**Pull request closed without merging**
